
const INCREMENT = 'INCREMENT'
const DECREMENT = 'DECREMENT'
const SET_USER_IDENTITY = 'SET_USER_IDENTITY'
const SET_USER_REPORT_GROUP = 'SET_USER_REPORT_GROUP'

export default {
  INCREMENT,
  DECREMENT,
  SET_USER_IDENTITY,
  SET_USER_REPORT_GROUP,
}
